### ISSUE TITLE
GSC needs the owner of a given property

### ISSUE THREAD

**Issue by michaeljfriedman** [LK/monopoly-simulator#5]
In `GameStateChange`'s `mortgage()`, `unmortgage()`, `build()`, and `demolish()` static methods, only the property to be modified and the bank should be passed in. However, `GameStateChange` needs to get the owner of a property to implement these operations given _only_ those parameters, and the API currently only supports getting the owner of a property from the `GameState`.

**Comment by LK** [comment]
So you're just looking for a more elegant solution than passing in `player` directly (as is done now), right?

**Comment by michaeljfriedman** [comment]
Yes, though this is something I think we should discuss in more detail

**Comment by LK** [comment]
I don't think option 1 is _that_ bug-prone simply because ownership changes can only happen when applying a `GameStateChange`, so there is really only one place where consistency needs to be maintained. That being said, it's definitely the hackier of the two options.

That being said, option 2 might be a bit overkill/overcomplicated for this purpose. I think it makes sense for a property to keep a reference to its owner, so IMO that's the best option for now.

**Comment by michaeljfriedman** [comment]
Or I suppose there's option 3, which is to just pass `state` to those methods instead of `bank`, and then call `state.get_owner()` to get a reference to the player and `state.bank` for the bank. It's probably also the most straight-forward solution.

**Comment by LK** [comment]
Yep, I think I like that the most. At some point we should probably look into some minor re-architecting to resolve some of these convoluted dependencies, but personally I'd rather get something working first.
